"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
var pinia_1 = require("pinia");
var App_vue_1 = require("./App.vue");
var router_1 = require("./router");
require("./assets/main.css");
// UI Components
var Button_vue_1 = require("./components/ui/Button.vue");
var Input_vue_1 = require("./components/ui/Input.vue");
var Textarea_vue_1 = require("./components/ui/Textarea.vue");
var Select_vue_1 = require("./components/ui/Select.vue");
var SelectOption_vue_1 = require("./components/ui/SelectOption.vue");
var Label_vue_1 = require("./components/ui/Label.vue");
var Switch_vue_1 = require("./components/ui/Switch.vue");
var Card_vue_1 = require("./components/ui/Card.vue");
var CardHeader_vue_1 = require("./components/ui/CardHeader.vue");
var CardTitle_vue_1 = require("./components/ui/CardTitle.vue");
var CardContent_vue_1 = require("./components/ui/CardContent.vue");
var CardFooter_vue_1 = require("./components/ui/CardFooter.vue");
var Table_vue_1 = require("./components/ui/Table.vue");
var TableHeader_vue_1 = require("./components/ui/TableHeader.vue");
var TableBody_vue_1 = require("./components/ui/TableBody.vue");
var TableRow_vue_1 = require("./components/ui/TableRow.vue");
var TableHead_vue_1 = require("./components/ui/TableHead.vue");
var TableCell_vue_1 = require("./components/ui/TableCell.vue");
var Pagination_vue_1 = require("./components/ui/Pagination.vue");
var PaginationContent_vue_1 = require("./components/ui/PaginationContent.vue");
var PaginationItem_vue_1 = require("./components/ui/PaginationItem.vue");
var PaginationLink_vue_1 = require("./components/ui/PaginationLink.vue");
var PaginationPrevious_vue_1 = require("./components/ui/PaginationPrevious.vue");
var PaginationNext_vue_1 = require("./components/ui/PaginationNext.vue");
var PaginationEllipsis_vue_1 = require("./components/ui/PaginationEllipsis.vue");
var Skeleton_vue_1 = require("./components/ui/Skeleton.vue");
var app = (0, vue_1.createApp)(App_vue_1.default);
// Register UI components globally
app.component('Button', Button_vue_1.default);
app.component('Input', Input_vue_1.default);
app.component('Textarea', Textarea_vue_1.default);
app.component('Select', Select_vue_1.default);
app.component('SelectOption', SelectOption_vue_1.default);
app.component('Label', Label_vue_1.default);
app.component('Switch', Switch_vue_1.default);
app.component('Card', Card_vue_1.default);
app.component('CardHeader', CardHeader_vue_1.default);
app.component('CardTitle', CardTitle_vue_1.default);
app.component('CardContent', CardContent_vue_1.default);
app.component('CardFooter', CardFooter_vue_1.default);
app.component('Table', Table_vue_1.default);
app.component('TableHeader', TableHeader_vue_1.default);
app.component('TableBody', TableBody_vue_1.default);
app.component('TableRow', TableRow_vue_1.default);
app.component('TableHead', TableHead_vue_1.default);
app.component('TableCell', TableCell_vue_1.default);
app.component('Pagination', Pagination_vue_1.default);
app.component('PaginationContent', PaginationContent_vue_1.default);
app.component('PaginationItem', PaginationItem_vue_1.default);
app.component('PaginationLink', PaginationLink_vue_1.default);
app.component('PaginationPrevious', PaginationPrevious_vue_1.default);
app.component('PaginationNext', PaginationNext_vue_1.default);
app.component('PaginationEllipsis', PaginationEllipsis_vue_1.default);
app.component('Skeleton', Skeleton_vue_1.default);
app.use((0, pinia_1.createPinia)());
app.use(router_1.default);
app.mount('#app');
